### PR TITLE
Delete FUNDING.yml

### PR DESCRIPTION
**Pull request by ellenhp**
I'm no longer maintaining this software.

### CODE REVIEW

**Comment by ellenhp** [comment]
I should probably also delete the entire .github directory.

**Comment by ellenhp** [comment]
Wait no that's where the CI config goes. Jeez it's been a minute since I've touched this :sweat_smile: Will open another PR from my fork.

**Comment by michaelkirk** [comment]
Yup, I'm still using most of .github! 

Though I've only just now realized that I haven't been using the "branded" containers for maps.earth. Werps.

**Comment by ellenhp** [comment]
Not a big deal. Feel free to go merge #194 btw. I don't want to solicit donations for software I don't maintain.

**Pull request closed without merging**
