### PR TITLE
Compress processed data and use pbzip2 for (de)compression

### PR DESCRIPTION
**Pull request by ellenhp**
This just makes things a bit more uniform which is nice. It also shrinks the nominatim.sql artifacts dramatically.

### CODE REVIEW

**Comment by ellenhp** [comment]
Looks like this introduced a regression with the valhalla tile generation. Investigating.

**Comment by 3nprob** [comment]
Just curious, are there any particular motivations behind choosing `pbzip2` specifically?

**Comment by ellenhp** [comment]
I only know about it because it's what GraphHopper suggests you use for decompressing their planet-scale photon index tarballs. It seems quite a bit faster than some alternatives, which is the main reason I'm using it. Know of anything that's faster that still has decent compression? It wasn't something I thought through fully, I was just trying to standardize on one thing and it seemed better than gzip if I'm targeting planet-scale data.

**Comment by 3nprob** [comment]
Thanks for the context!

I haven't done any benchmarking on the format of data here - which is what it would come down to to do reliably better than intuition. Defaulting to what what GraphHopper recommends and uses for photon data sounds good. Also comes down to if what performance dimension is optimized for. IME zstd tends to be a sane generic default where decompression and compression speeds are prioritized but again, depending on the data it may not be the case ^^

bzip2 should be good until there is evidence for something else being better here specifically.

**Comment by ellenhp** [comment]
The compression format isn't the source of the regression, I think I was just over-eager with how I extracted it. Valhalla expects an uncompressed but not un-tarred archive on startup, and I was fully extracting it.

**Comment by ellenhp** [comment]
Thank you for the rest of the input btw!!! I really like having someone review things even if it's async because I absolutely miss things and just make weird assumptions sometimes.

**Comment by 3nprob** [comment]
You may even want one algo for dev (you want as fast compress performance as you can for quick iterations and not hogging your workstation CPU) than prod (where you may be happy spending more on infrequent compressions for better runtime and application startup performance).

But that's prob premature to start thinking about unless its a practical issue already.

**Pull request merged**
