### PR TITLE
Bikeshed the image at the top of the readme.

### PR DESCRIPTION
**Pull request by xorgy**
Far as I'm aware, this should be equivalent (uses currentColor based on prefers-color-scheme), and the file is smaller. ;= )

### CODE REVIEW

**Comment by ellenhp** [comment]
Looking at the branch here shows a white image on white background: https://github.com/xorgy/headway/tree/bikeshed

I'm also going to ask you to crop the image to be a bit more rectangular (reduce padding at top and bottom) and to switch the usage of that image to use normal Markdown syntax now that we don't need the fancy HTML magic anymore. But I'm very happy bikeshedding away binary files so thank you for this :)

**Comment by ellenhp** [comment]
Also even if you can't get the color switching working we could just replace both the light and dark pngs with svgs, and manually flip the color value from #000000 to #FFFFFF. Even if one SVG doesn't end up working, two SVGs is better than two PNGs.

**Comment by xorgy** [comment]
Hmm, the switching seems to work fine for me in Chrome, and I tried it in Firefox too.
Android Chrome light mode
Android Chrome dark mode

**Comment by xorgy** [comment]
As for the padding, I matched your image exactly, but I can change that too. :+ )

**Comment by ellenhp** [comment]
Dark mode looks fine for me but light mode shows the dark mode configuration. What's weird about my configuration is that I have github forced to light mode because I don't like their implementation but my system is set to use dark mode. It's possible that when the browser renders the SVG it uses the system settings instead of the settings github has asked it to use.

**Comment by xorgy** [comment]
> Dark mode looks fine for me but light mode shows the dark mode configuration. What's weird about my configuration is that I have github forced to light mode because I don't like their implementation but my system is set to use dark mode. It's possible that when the browser renders the SVG it uses the system settings instead of the settings github has asked it to use.

Yeah, that's how it's gonna work, in that case the scheme in the page is what you want, but what you're getting is the configured scheme, and that requires the `<picture>` hax. :+ )

**Comment by ellenhp** [comment]
Do you want to switch this PR to use the `<picture>` hax with two SVGs?

**Comment by xorgy** [comment]
Feel free to shquashmerge.

**Comment by ellenhp** [comment]
Looks great. I haven't been squashing commits for this project in general. I'm not going to bother approving this for CI because I anticipate running out of free CI minutes this month and this is the lowest risk PR I can imagine. Just going to merge straight to main yolo. :)

**Pull request merged**
