### PR TITLE
Script to deploy Headway

### PR DESCRIPTION
**Pull request by kresp0**
Tested on Debian 11. It should also work on Ubuntu and other Debian-based distros.

### CODE REVIEW

**Comment by kresp0** [comment]
After the install finishes, it is possible to check the status, stop, start and restart the Headway service:
`sudo service headway status`
`sudo service headway stop`
`sudo service headway start`
`sudo service headway restart`

But doing a reload will download and build the latest Headway, get fresh data and reprocess everything:
`sudo service headway reload`

**Comment by ellenhp** [comment]
I don't have a VM ready to go for testing, and if I'm going to merge this without personally testing testing I want to make sure we set expectations well.

Could you add documentation about this in `BUILD.md` and mention that the script was contributed by you? I want to a) attribute your work, and b) make sure people know that this isn't necessarily something that has been widely used quite yet.

**Comment by kresp0** [comment]
Done ✔️

**Comment by ellenhp** [comment]
Here, and in #171, last nit-pick I promise but could you move this script and DEBIAN_BUILD.md into a top-level `contrib/` directory? I anticipate more things like this potentially happening in the future and want to keep contributed scripts and utilities separate.

https://drewdevault.com/2020/06/06/Add-a-contrib-directory.html

**Comment by kresp0** [comment]
Done ✔️

**Pull request merged**
